HomePage
toca-do-javascript/marketplace-nft-frontend pull request #19
Opened 2023-06-08 18:33 UTC by jeffszo

Merge entre a Homepage e a Main

2023-06-08 18:36 UTC, DevIgorRafaelDeMelo approved these changes

2023-06-08 21:33 UTC, ryanpaiva reviewed
Branch tá desatualizada.

2023-06-08 21:34 UTC, ryanpaiva commented on src/Ui/Components/Button/Button.jsx
> +import "../../../../variable.css";
componente do button está com uma branch desatualizada.

2023-06-08 21:36 UTC, ryanpaiva commented on package-lock.json
> -{
package-lock.json não deveria estar no projeto.

2023-06-08 21:40 UTC, ryanpaiva commented on src/Pages/Sign/Sign.jsx
> +const ButtonLogin = styled.div`
const ButtonLogin não existe mais.

2023-06-09 04:03 UTC, Dehrangerz9 commented
Da um pull da main no homepage, pra ficar mais atualizado.

2023-06-10 19:20 UTC, ryanpaiva commented on src/Pages/Sign/Sign.jsx
> +    const Button = styled.div`
página sign in não está como na branch main

2023-06-10 19:21 UTC, ryanpaiva commented on src/Pages/Sign/Sign.jsx
> +        console.log(values)
Retirar console.log

2023-06-14 20:52 UTC, Dehrangerz9 requested changes, later dismissed
Até então a parte que você fez funcionaram, contudo, o register ficou quebrado. Se você conseguir arrumar isso ai, da para aprovar.

2023-06-14 20:52 UTC, Dehrangerz9 commented on src/App.jsx
> +          <Route path='/register' element={<Register/>} />
Por algum motivo, o register não está mais funcionando.

2023-06-14 20:52 UTC, Dehrangerz9 commented on src/Ui/Components/Input/Input.jsx
> -`;
Porque foi editado o componente input? Isso quebrou o componente.

2023-06-14 20:52 UTC, Dehrangerz9 commented on src/Pages/Sign/Sign.jsx
O seu arquivo de Login está desatualizado, esse é o antigo.

2023-06-14 20:53 UTC, Dehrangerz9 commented on src/App.jsx
> +          <Route path='/register' element={<Register/>} />
Edit - descobri o motivo, o componente input está quebrado.

2023-06-15 22:22 UTC, pedro3g approved these changes

2023-06-15 22:23 UTC, davi-aalves approved these changes

2023-06-15 22:26 UTC, merged